spring:
  application:
    name: gateway-web
  #跨域配置
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #唯一标识符
        - id: changgou_goods_route
          #用户的请求需要路由到该服务
          #uri: http://localhost:18081
          #lb: 使用LoadBalanceCient 实现负载均衡,后面goods是微服务的名称[主要应用于集群环境]
          uri: lb://goods
          #路由断言,配置路由规则
          predicates:
            #用户请求的域名规则配置,所有以cloud.itheima.com的请求都将被路由到以上uri
            - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
            #- Host=cloud.itheima.com**
          filters:
            #给以上-path 例如-path=** 指定路径前添加一个指定前缀,并路由到上面的uri,不与下面的- StripPrefix一起用,无意义
            #- PrefixPath=/brand
            #将请求路径中的第一个路径去掉,以/区分路径,配合-path就是将上面指定的api开头的url去掉一个路径(/api)
            - StripPrefix=1
            #局部限流过滤器
            - name: RequestRateLimiter #请求数限流 名字不能随便改 使用默认的facatory
              args:
                key-resolver: "#{@ipKeyResolver}"
                #每秒只允许有1个请求
                redis-rate-limiter.replenishRate: 1
                #允许并发有4个请求 [宽限的个数]
                redis-rate-limiter.burstCapacity: 4

          #用户微服务
        - id: changgou_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
          #认证微服务
        - id: changgou_oauth_user
          uri: lb://user-auth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
        #订单微服务
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1
        #购物车订单渲染微服务
        - id: changgou_order_web_route
          uri: lb://order-web
          predicates:
            - Path=/api/wcart/**,/api/worder/**
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.6.130
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true